# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-13 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('device_token', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'ordering': ('user_id',),
            },
        ),
    ]
