# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-22 14:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('micell', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referralaff',
            name='referred',
        ),
        migrations.RemoveField(
            model_name='referralaff',
            name='referrer',
        ),
        migrations.DeleteModel(
            name='ReferralAff',
        ),
    ]
